// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427111353_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f516b57-8115-4bc6-8720-ec7eae4f93c8"),
                            CountryName = "Finland"
                        },
                        new
                        {
                            Id = new Guid("06706ac8-6f04-44eb-8e02-c545dbad1633"),
                            CountryName = "Norway"
                        },
                        new
                        {
                            Id = new Guid("ce4fb821-68f4-4c06-b16f-7d44647f2d41"),
                            CountryName = "China"
                        },
                        new
                        {
                            Id = new Guid("40ea2121-b73c-4dce-8d95-368846a15abe"),
                            CountryName = "Estonia"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("peoples", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Adress = "Helsinki, Finland",
                            CountryId = new Guid("7f516b57-8115-4bc6-8720-ec7eae4f93c8"),
                            DateOfBirth = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.smith@example.com",
                            Gender = "Male",
                            PersonName = "John Smith",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Adress = "Shanghai, China",
                            CountryId = new Guid("ce4fb821-68f4-4c06-b16f-7d44647f2d41"),
                            DateOfBirth = new DateTime(1988, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "li.wei@example.com",
                            Gender = "Male",
                            PersonName = "Li Wei",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Adress = "Tallinn, Estonia",
                            CountryId = new Guid("40ea2121-b73c-4dce-8d95-368846a15abe"),
                            DateOfBirth = new DateTime(1997, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.kask@example.com",
                            Gender = "Female",
                            PersonName = "Anna Kask",
                            ReceiveNewsLetters = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
